// frontend/src/constants/productionOrderConstants.js

// Üretim Siparişleri Listeleme Sabitleri
export const PRODUCTION_ORDER_LIST_REQUEST = 'PRODUCTION_ORDER_LIST_REQUEST';
export const PRODUCTION_ORDER_LIST_SUCCESS = 'PRODUCTION_ORDER_LIST_SUCCESS';
export const PRODUCTION_ORDER_LIST_FAIL = 'PRODUCTION_ORDER_LIST_FAIL';

// Üretim Siparişi Detay Sabitleri
export const PRODUCTION_ORDER_DETAILS_REQUEST = 'PRODUCTION_ORDER_DETAILS_REQUEST';
export const PRODUCTION_ORDER_DETAILS_SUCCESS = 'PRODUCTION_ORDER_DETAILS_SUCCESS';
export const PRODUCTION_ORDER_DETAILS_FAIL = 'PRODUCTION_ORDER_DETAILS_FAIL';

// Üretim Siparişi Oluşturma Sabitleri
export const PRODUCTION_ORDER_CREATE_REQUEST = 'PRODUCTION_ORDER_CREATE_REQUEST';
export const PRODUCTION_ORDER_CREATE_SUCCESS = 'PRODUCTION_ORDER_CREATE_SUCCESS';
export const PRODUCTION_ORDER_CREATE_FAIL = 'PRODUCTION_ORDER_CREATE_FAIL';
export const PRODUCTION_ORDER_CREATE_RESET = 'PRODUCTION_ORDER_CREATE_RESET';

// Üretim Siparişi Güncelleme Sabitleri
export const PRODUCTION_ORDER_UPDATE_REQUEST = 'PRODUCTION_ORDER_UPDATE_REQUEST';
export const PRODUCTION_ORDER_UPDATE_SUCCESS = 'PRODUCTION_ORDER_UPDATE_SUCCESS';
export const PRODUCTION_ORDER_UPDATE_FAIL = 'PRODUCTION_ORDER_UPDATE_FAIL';
export const PRODUCTION_ORDER_UPDATE_RESET = 'PRODUCTION_ORDER_UPDATE_RESET';

// Üretim Siparişi Silme Sabitleri
export const PRODUCTION_ORDER_DELETE_REQUEST = 'PRODUCTION_ORDER_DELETE_REQUEST';
export const PRODUCTION_ORDER_DELETE_SUCCESS = 'PRODUCTION_ORDER_DELETE_SUCCESS';
export const PRODUCTION_ORDER_DELETE_FAIL = 'PRODUCTION_ORDER_DELETE_FAIL';
